#!/bin/bash

# Quick install instructions for Ubuntu 18.04 Linux:

# Spidermonkey:
# sudo apt install libmozjs-52-0 libmozjs-52-dev
# installs as /usr/bin/js52

# Node.js, which uses V8 as its JavaScript engine:
# sudo apt install nodejs
# installs as /usr/bin/nodejs

if [ "${NODEJS_CMD}" = "" -a "${SPIDERMONKEY_CMD}" = "" ]; then
    echo "Neither NODEJS_CMD nor SPIDERMONKEY_CMD is set, cannot run tests"
    exit 1
fi

rm -rf out
mkdir -p out
lein with-profile +cljs cljsbuild once test
echo "Launching test runner..."

if [ "${NODEJS_CMD}" != "" ]; then
    echo "Testing with Node.js:"
    "${NODEJS_CMD}" -e 'require("./out/test"); clojure.core.rrb_vector.test_cljs.run()'
fi

if [ "${SPIDERMONKEY_CMD}" != "" ]; then
    echo "Testing with SpiderMonkey:"
    "${SPIDERMONKEY_CMD}" -f out/test.js "--execute=clojure.core.rrb_vector.test_cljs.run()"
fi
