#!/bin/bash

# See README.md for some sample install instructions for Ubuntu 18.04
# Linux and macOS.  If you use those instructions, then the following environment variable settings should work:

# export NODEJS_CMD="node"
# export SPIDERMONKEY_CMD="js52"

if [ "${NODEJS_CMD}" = "" -a "${SPIDERMONKEY_CMD}" = "" ]; then
    echo "Neither NODEJS_CMD nor SPIDERMONKEY_CMD is set, cannot run tests"
    exit 1
fi

rm -rf out
mkdir -p out
lein with-profile +cljs cljsbuild once test
echo "Launching test runner..."

if [ "${NODEJS_CMD}" != "" ]; then
    echo "Testing with Node.js:"
    "${NODEJS_CMD}" -e 'require("./out/test"); clojure.core.rrb_vector.test_cljs.run()'
fi

if [ "${SPIDERMONKEY_CMD}" != "" ]; then
    echo "Testing with SpiderMonkey:"
    "${SPIDERMONKEY_CMD}" -f out/test.js "--execute=clojure.core.rrb_vector.test_cljs.run()"
fi
