#!/bin/bash

if [ "${V8_HOME}" = "" -a "${SPIDERMONKEY_HOME}" = "" ]; then
    echo "Neither V8_HOME nor SPIDERMONKEY_HOME is set, cannot run tests"
    exit 1
fi

rm -rf out
mkdir -p out
lein with-profile +cljs cljsbuild once test
echo "Launching test runner..."

if [ "${V8_HOME}" != "" ]; then
    echo "Testing with V8:"
    "${V8_HOME}/d8" out/test.js
fi

if [ "${SPIDERMONKEY_HOME}" != "" ]; then
    echo "Testing with SpiderMonkey:"
    "${SPIDERMONKEY_HOME}/js" -f out/test.js
fi
